[package]
name = "bethon"
version = "0.1.0"
authors = ["Vinícius Regatieri <viniciusvcr@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.3.0"
num-traits = "0.2.12"